### ISSUE TITLE
Where are the /apps/  /fceugx/ and /roms/ folder mentioned here http://www.howtogeek.com/139638/how-to-play-retro-nes-and-snes-games-on-your-nintendo-wii/

### ISSUE THREAD

**Issue by mattlee0037** [dborth/fceugc#343]
Tried adding the extracted contents to the root of my SD card and to the /apps folder for homebrew however there isn't even a ROM folder so I am unsure how this is even supposed to work.

**Comment by TomatoHentai** [comment]
You have to build it, I'm pretty sure.

**Comment by dborth** [comment]
https://github.com/dborth/fceugc/releases
